## Take an input matrix with size 5x5 and a kernel with size 3x3, perform convolution with stride being 1 and 2.


In [2]:
#returns the size of the output matrix

def output_size(input_size, kernel_size, padding, stride):
    size = ((input_size + 2 * padding - kernel_size)/stride + 1)         
    return int(size)


In [21]:
def convolution(input_mat, kernel, padding, stride):
    size = output_size(input_mat.shape[0], kernel.shape[0], padding, stride)
    #print("size = ", size)
    output = []
    for y in range(input_mat.shape[1]):
        # loop exits at the end of matrix
        if y > input_mat.shape[1] - kernel.shape[1]:
            break
            # runs for specified Strides
        if y % stride == 0:
                for x in range(input_mat.shape[0]):
                    # avoiding out of bounds at end of matrix
                    if x > input_mat.shape[0] - kernel.shape[0]:
                        break
        
                    # Runs for particular value according to Strides
                    if x % stride == 0:
                        #print((kernel * input_mat[x: x + kernel.shape[0], y: y + kernel.shape[1]]).sum())
                        val = (kernel * input_mat[x: x + kernel.shape[0], y: y + kernel.shape[1]]).sum()
                        #print(val)
                        output.append(val)
                        #print(output)
    
    matrix = np.array(output)
    output_mat = matrix.reshape(size, size)
                
    return output_mat

In [13]:
import numpy as np

input_mat = np.random.randint(10, size = (5, 5))
kernel = np.random.randint(5, size = (3,3))
print("\nInput Matrix : \n")
print(input_mat)
print("\n\nKernel : \n")
print(kernel)


Input Matrix : 

[[5 1 1 2 2]
 [3 9 9 9 6]
 [1 8 4 4 9]
 [8 1 8 9 7]
 [8 9 0 9 6]]


Kernel : 

[[2 3 2]
 [2 1 1]
 [1 0 0]]


<br>

<br>

Final output matrix with stride= 1

In [22]:
#output with stride = 1
convolution(input_mat, kernel, 0 , 1)

array([[40, 73, 67],
       [53, 88, 64],
       [49, 86, 70]])

<br>

<br>
Final output matrix with stride= 2

In [23]:
#output with stride = 2
convolution(input_mat, kernel, 0 , 2)

array([[40, 67],
       [49, 70]])